<a href="https://colab.research.google.com/github/olyviah82/AI/blob/main/Notebook1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

In [3]:
uniform(10,50)

40.73122901935922

Dataset

In [ ]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],'Day 3':[50,20,15,60,70,50],
      'Target':[20,15,60,70,50,40]}

In [ ]:
pd.DataFrame(data)

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [ ]:
X=dataset.drop('Target', axis=1)
y=dataset['Target']

In [ ]:
X_norm=Normalizer(norm='max').fit_transform(X)

In [ ]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [ ]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [ ]:
array([[1,2,3]]).shape

(1, 3)

In [ ]:
np.reshape(array(y),(1,-1))

(1, 6)

In [ ]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [ ]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [ ]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

ANN From Scratch

In [ ]:
weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])

In [ ]:
weight_1=uniform(-1,1(3,2))

weight_2=uniform(-1,1(2,1))

TypeError: ignored

In [ ]:
output_1 = X_norm[0]@weight_1
output_1

array([0.56, 0.24])

In [ ]:
act_output=sigmoid(output_1).numpy()
act_output

array([0.63645254, 0.55971365])

In [ ]:
pred_output=act_output@weight_2
pred_output

array([0.37419764])

Mean Squared Error

In [ ]:
y_true=np.reshape(y_norm[0][0:batch_size],(-1,1))
y_pred=pred_output

In [ ]:
np.reshape(y_true,(-1,1))

array([[0.28571429]])

In [ ]:
mse(y_true,y_pred).numpy()

0.007829303112763407